import { PALETTE } from "../palettes";
import { TitleScene } from "../scenes/TitleScene";
import { Level } from "../types";

const name = 'portal';

export const TUTORIAL_LEVEL_30: Level = {
  name,
  timeToClear: 1000 * 60 * 5,
  applesToClear: 49,
  numApplesStart: -1,
  disableAppleSpawn: true,
  snakeStartSizeOverride: 20,
  // growthMod: 0,
  layout: `
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXXXXDDXXDDXXXXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXXXXDDXXDDXXXXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X aaaaaaaaaaaaaaaaaaa------=1X
X aaaaaaaaaaaaaaaaaaa------=1X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX===O    aaaaaaaaaaaaaaaaa=1X
X2---     -----------------=1X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X2aaaaa--aaaaa--aaaaa--aaaaaDD
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXXXXDDXXDDXXXXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
XXXXXXXXXXXXDDXXDDXXXXXXXXXXXX
XXXXXXXXXDDXDDXXDDXDDXXXXXXXXX
  `,
  colors: PALETTE.mintJulip,
  titleScene: (p5, sfx, fonts, callbacks) => new TitleScene(name, p5, sfx, fonts, callbacks),
};
