import { MusicTrack } from "../../types";
import { toTime } from "../../utils";
import { v2Level } from "../v2Level";

export const LEVEL_16 = v2Level({
  id: 'C16',
  name: 'scantron',
  parTime: toTime({ minutes: 1, seconds: 15 }),
  layoutV2: `CnlOWGRPLS0tLS0hTEwhLSF6ZE5QTkFkT0FBQUEtIUxMIS1BQUFBVWRqTgpYZGRkTyF6KVhzc35PLS0tLVVkZGRiKSFRISlQaWRLLSooISpOWWdOISpTVSlYWWd%252BTyFTLSFocFd%252Bd1opXyFKTExMSkohXykpUHVrbXVBbX4pXyFKSkxMTEohX1p3KSlQV2RLLSpoaFNVKVhHR35PIVMqTkdHTiEqcGl%252BIVEhKWJkZGRPLS0tLVUpWHNzfk8hemRkZFBObGRPQUFBQS0hSkohLUFBQUFVZEFOCk5YZE8hTyFKSiEtLS0tLVVkTlB5fDcyNnxSSUdIVHxzY2FudHJvbnwxODAwMHE2cXFxNXwwLjE1fDI1fDF8IzY4QjJBOVY0ODhDODRWMUQyMDIwVkU3NkQ4M1ZFMjUwNkFWMjYyQTJCVjFEMjAyMFYzMDM0MzZWMjYyQTJCVjk3ODc4RlY2MjU2NUNWRkZGNkYxVjBBMEUxNFZFOUVGRkZ8eHh4cTl8MCEqIGU9KSwnKiAgTlhYei1QWApRKChlTk1NTigoZVNwZEstKighVS0gVi0jV1h2LT0gKE8tT1UoTy1PVSggPS12UFopKVB%252BKSlOTilPKkpKSkoqVSlOTikpKVB%252BX05OTmJQfiEhISBOc3NOISEhIClQWGUoPWgoIS0haVh2LT0gUSA9LXZQbUFMSmVmZk1Nc3NkZEgKcCgqLUtkCnEwfHVIZGRzc01NZmZlSkx3KSkgaGgoICl4MC0wLTAteV9fTkhIX19OCnpPIH5YKQF%252Benl4d3VxcG1paGViX1pXVlVTUVBPTiopKCFf`,
  musicTrack: MusicTrack.conquerer,
});
