
import { MusicTrack } from "../../types";
import { challengeLevel } from "./_challengeLevel";
import { X_ACROPOLIS } from "./acropolis";

const name = 'snek city';

export const X_SNEKCITY = challengeLevel({
  id: 'X417',
  name,
  layoutV2: `b1hzc3NWdVhWLSEtc3NWKCdaIS1aIS0gWFhzVignWlVVd1hMcy0uKHItJyp3aSdVVi4ocnRpJ1VWLnVYSlhldFhlKmdlJ1hpWC1aWGUqZ1kqaUFYYmknZ1kqTEFMWGJBTFgtZ1lYVylYYkxBWC1nWVhXVmJpWC1VVihYWVhYKmhoKiEtIS5feGUhKFhYayk9KVhzX0xlIShKJyk9TEFpLilYS0tYTH5KV0oqaUFMLlhMQUx5eH4pZSApVyFYQWl5QX4pZSEuPSFYaVlfQVdjKWUtVVUgTFV5QVdjYS1VckxVJ1h4fm5YKmxfTFdjbjMnKlhMV2ZZYT1hYUpYeFdmWFUnKlgzeEFBQUFBQXhpJypmWSkgZWFhJypjai5lcnIqSnJyWG98NDAyfFJJR0hUfE1FR0FTTkVLT1BPTElTcDJ2Njd8M3x2M3BwMnB8IzE1QzJDQlExMTlEQTRxMjM3NThRMkU0QTc2enE3MkMzRnpRNEM4MkE5UTNGNkM4RFFGRkY2RjFRMEEwRTE0UUU5RUZGRnxtbW12Ny4gKj0odVkpWFhYKic9LiEgUS0jVSAnViEhV1g9WVggdy1fPVhhKSliLS0taVhjeHg9KGVYJ2Z4eC1kCmdWLihYaFVaLS1WclYoWFcpJ2lMTG0wLTAtMC1uZHhBQXhkIGFYbwphYWFhYQpwfDFxUTE2MTkyNVEycicnc1ZWdC0nKi0tIHVYCnYwfHdaIHkgX3pRMUYyMzMzfmUnKAF%252Benl3dnV0c3JxcG9ubWloZ2ZlY2JhX1pZV1ZVUS4qKSgnIV8%253D`,
  musicTrack: MusicTrack.lordy,
  nextLevel: X_ACROPOLIS,
});
