import assert from "assert";
import { AnimationList, INITIAL_ANIMATIONS_POOL_SIZE } from "../../collections/animationList";
import { getCoordIndex2 } from "../../utils";
import { GRIDCOUNT } from "../../constants";

describe("Collections", () => {
  describe("AnimationList", () => {
    it("should initialize items", () => {
      const items = new AnimationList();
      assert.strictEqual(items.getLength(), 0);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), false);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), false);
      assert.strictEqual(items.existsAt(4, 4), false);
    });
    it("should add items", () => {
      const items = new AnimationList();
      assert.strictEqual(items.length, 0);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), false);
      assert.strictEqual(items.existsAt(4, 4), false);
      items.add(3, 3, 1000);
      items.add(4, 4, 1000);
      assert.strictEqual(items.length, 2);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), true);
      assert.strictEqual(items.existsAt(4, 4), true);
    });
    it("should remove items", () => {
      const items = new AnimationList();
      items.add(10, 1, 9999);
      items.add(1, 10, 9999);
      assert.strictEqual(items.getLength(), 2);
      assert.strictEqual(items.existsAt(10, 1), true);
      assert.strictEqual(items.existsAt(1, 10), true);
      items.remove(10, 1);
      assert.strictEqual(items.getLength(), 1);
      assert.strictEqual(items.existsAt(10, 1), false);
      assert.strictEqual(items.existsAt(1, 10), true);
      items.remove(1, 10);
      assert.strictEqual(items.existsAt(10, 1), false);
      assert.strictEqual(items.existsAt(1, 10), false);
    });
    it("should reset apples", () => {
      const items = new AnimationList();
      items.add(1, 1, 9999);
      items.add(2, 2, 9999);
      items.add(3, 3, 9999);
      items.add(4, 4, 9999);
      items.add(5, 5, 9999);
      items.add(6, 6, 9999);
      items.add(7, 7, 9999);
      items.add(8, 8, 9999);
      items.add(9, 9, 9999);
      items.add(10, 10, 9999);
      assert.strictEqual(items.length, 10);
      assert.strictEqual(items.existsAt(5, 5), true);
      items.reset();
      assert.strictEqual(items.length, 0);
      assert.strictEqual(items.existsAt(5, 5), false);
    });
    it("should ignore adding duplicates", () => {
      const items = new AnimationList();
      items.add(1, 1, 9999);
      items.add(1, 1, 8888);
      items.add(1, 1, 7777);
      items.add(1, 1, 6666);
      items.add(1, 1, 5555);
      items.add(10, 10, 9999);
      items.add(10, 10, 8888);
      items.add(10, 10, 7777);
      items.add(10, 10, 6666);
      items.add(10, 10, 5555);
      assert.strictEqual(items.length, 2);
      assert.strictEqual(items.existsAt(1, 1), true);
      assert.strictEqual(items.existsAt(10, 10), true);
      assert.strictEqual(items.getLifetime(1, 1), 9999);
      assert.strictEqual(items.getLifetime(10, 10), 9999);
    });
    it("should remove item by coord", () => {
      const items = new AnimationList();
      items.add(1, 1, 9999);
      items.add(2, 2, 9999);
      items.add(3, 3, 9999);
      items.add(4, 4, 9999);
      items.add(5, 5, 9999);
      assert.strictEqual(items.getLength(), 5);
      assert.strictEqual(items.existsAt(1, 1), true);
      assert.strictEqual(items.existsAt(2, 2), true);
      assert.strictEqual(items.existsAt(3, 3), true);
      assert.strictEqual(items.existsAt(4, 4), true);
      assert.strictEqual(items.existsAt(5, 5), true);
      items.removeByCoord(getCoordIndex2(3, 3));
      assert.strictEqual(items.getLength(), 4);
      assert.strictEqual(items.existsAt(1, 1), true);
      assert.strictEqual(items.existsAt(2, 2), true);
      assert.strictEqual(items.existsAt(3, 3), false);
      assert.strictEqual(items.existsAt(4, 4), true);
      assert.strictEqual(items.existsAt(5, 5), true);
    });
    it("should get item exists by coord", () => {
      const items = new AnimationList();
      items.add(1, 1, 9999);
      items.add(2, 2, 9999);
      items.add(3, 3, 9999);
      items.add(4, 4, 9999);
      items.add(5, 5, 9999);
      assert.strictEqual(items.getLength(), 5);
      assert.strictEqual(items.existsAtCoord(getCoordIndex2(0, 0)), false);
      assert.strictEqual(items.existsAtCoord(getCoordIndex2(1, 1)), true);
      assert.strictEqual(items.existsAtCoord(getCoordIndex2(2, 2)), true);
      assert.strictEqual(items.existsAtCoord(getCoordIndex2(3, 3)), true);
      assert.strictEqual(items.existsAtCoord(getCoordIndex2(4, 4)), true);
      assert.strictEqual(items.existsAtCoord(getCoordIndex2(5, 5)), true);
      assert.strictEqual(items.existsAtCoord(getCoordIndex2(6, 6)), false);
    });
    it("should support full grid of items", () => {
      const items = new AnimationList();
      assert.strictEqual(items.getLength(), 0);
      assert.strictEqual(items.getMaxLength(), INITIAL_ANIMATIONS_POOL_SIZE);
      for (let i = 0; i < INITIAL_ANIMATIONS_POOL_SIZE; i++) {
        const x = Math.floor(i % GRIDCOUNT.x);
        const y = Math.floor(i / GRIDCOUNT.x);
        items.add(x, y, 9999);
        assert.strictEqual(items.getLength(), i + 1);
        assert.strictEqual(items.existsAt(x, y), true);
      }
      assert.strictEqual(items.getLength(), INITIAL_ANIMATIONS_POOL_SIZE);
      assert.strictEqual(items.getMaxLength(), INITIAL_ANIMATIONS_POOL_SIZE);
    });
    it("should get closest traversal distance", () => {
      const items = new AnimationList();
      items.add(1, 1, 9999);
      items.add(2, 2, 9999);
      items.add(3, 3, 9999);
      items.add(4, 4, 9999);
      items.add(5, 5, 9999);
      assert(items.getClosestTraversalDistance(0, 0) === 2);
      assert(items.getClosestTraversalDistance(0, 1) === 1);
      assert(items.getClosestTraversalDistance(1, 1) === 0);
      assert(items.getClosestTraversalDistance(2, 2) === 0);
      assert(items.getClosestTraversalDistance(3, 3) === 0);
      assert(items.getClosestTraversalDistance(4, 4) === 0);
      assert(items.getClosestTraversalDistance(5, 5) === 0);
      assert(items.getClosestTraversalDistance(5, 6) === 1);
      assert(items.getClosestTraversalDistance(6, 6) === 2);
      assert(items.getClosestTraversalDistance(6, 7) === 3);
      assert(items.getClosestTraversalDistance(7, 7) === 4);
      assert(items.getClosestTraversalDistance(15, 15) === 20);
      items.removeByCoord(getCoordIndex2(1, 1));
      items.removeByCoord(getCoordIndex2(2, 2));
      items.removeByCoord(getCoordIndex2(3, 3));
      items.removeByCoord(getCoordIndex2(4, 4));
      assert(items.getClosestTraversalDistance(0, 0) === 10);
      assert(items.getClosestTraversalDistance(1, 1) === 8);
      assert(items.getClosestTraversalDistance(2, 2) === 6);
      assert(items.getClosestTraversalDistance(3, 3) === 4);
      assert(items.getClosestTraversalDistance(4, 4) === 2);
      assert(items.getClosestTraversalDistance(5, 5) === 0);
      assert(items.getClosestTraversalDistance(15, 15) === 20);
      items.removeByCoord(getCoordIndex2(5, 5));
      assert(items.getClosestTraversalDistance(0, 0) === Infinity);
      assert(items.getClosestTraversalDistance(1, 1) === Infinity);
      assert(items.getClosestTraversalDistance(2, 2) === Infinity);
      assert(items.getClosestTraversalDistance(3, 3) === Infinity);
      assert(items.getClosestTraversalDistance(4, 4) === Infinity);
      assert(items.getClosestTraversalDistance(5, 5) === Infinity);
      assert(items.getClosestTraversalDistance(6, 6) === Infinity);
      assert(items.getClosestTraversalDistance(6, 7) === Infinity);
      assert(items.getClosestTraversalDistance(7, 7) === Infinity);
      assert(items.getClosestTraversalDistance(15, 15) === Infinity);
    });
    it("should handle tick correctly", () => {
      const items = new AnimationList();
      items.add(0, 0, 0);
      items.add(1, 1, 1);
      items.add(2, 2, 2);
      items.add(3, 3, 3);
      items.add(4, 4, 4);
      items.add(5, 5, 5);
      assert.strictEqual(items.getLength(), 6);
      assert.strictEqual(items.getLifetime(0, 0), 0);
      assert.strictEqual(items.getLifetime(1, 1), 1);
      assert.strictEqual(items.getLifetime(2, 2), 2);
      assert.strictEqual(items.getLifetime(3, 3), 3);
      assert.strictEqual(items.getLifetime(4, 4), 4);
      assert.strictEqual(items.getLifetime(5, 5), 5);
      assert.strictEqual(items.getLifetime(6, 6), -1);
      assert.strictEqual(items.getLifetime(7, 7), -1);
      assert.strictEqual(items.existsAt(0, 0), true);
      assert.strictEqual(items.existsAt(1, 1), true);
      assert.strictEqual(items.existsAt(2, 2), true);
      assert.strictEqual(items.existsAt(3, 3), true);
      assert.strictEqual(items.existsAt(4, 4), true);
      assert.strictEqual(items.existsAt(5, 5), true);
      assert.strictEqual(items.existsAt(6, 6), false);
      assert.strictEqual(items.existsAt(7, 7), false);
      assert.strictEqual(items.getElapsed(0, 0), 0);
      assert.strictEqual(items.getElapsed(1, 1), 0);
      assert.strictEqual(items.getElapsed(2, 2), 0);
      assert.strictEqual(items.getElapsed(3, 3), 0);
      assert.strictEqual(items.getElapsed(4, 4), 0);
      assert.strictEqual(items.getElapsed(5, 5), 0);
      assert.strictEqual(items.getElapsed(6, 6), -1);
      assert.strictEqual(items.getElapsed(7, 7), -1);

      items.tick(1);

      assert.strictEqual(items.getLength(), 5);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), true);
      assert.strictEqual(items.existsAt(2, 2), true);
      assert.strictEqual(items.existsAt(3, 3), true);
      assert.strictEqual(items.existsAt(4, 4), true);
      assert.strictEqual(items.existsAt(5, 5), true);
      assert.strictEqual(items.existsAt(6, 6), false);
      assert.strictEqual(items.existsAt(7, 7), false);
      assert.strictEqual(items.getElapsed(0, 0), -1);
      assert.strictEqual(items.getElapsed(1, 1), 1);
      assert.strictEqual(items.getElapsed(2, 2), 1);
      assert.strictEqual(items.getElapsed(3, 3), 1);
      assert.strictEqual(items.getElapsed(4, 4), 1);
      assert.strictEqual(items.getElapsed(5, 5), 1);
      assert.strictEqual(items.getElapsed(6, 6), -1);
      assert.strictEqual(items.getElapsed(7, 7), -1);

      items.tick(1);

      assert.strictEqual(items.getLength(), 4);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), false);
      assert.strictEqual(items.existsAt(2, 2), true);
      assert.strictEqual(items.existsAt(3, 3), true);
      assert.strictEqual(items.existsAt(4, 4), true);
      assert.strictEqual(items.existsAt(5, 5), true);
      assert.strictEqual(items.existsAt(6, 6), false);
      assert.strictEqual(items.existsAt(7, 7), false);
      assert.strictEqual(items.getElapsed(0, 0), -1);
      assert.strictEqual(items.getElapsed(1, 1), -1);
      assert.strictEqual(items.getElapsed(2, 2), 2);
      assert.strictEqual(items.getElapsed(3, 3), 2);
      assert.strictEqual(items.getElapsed(4, 4), 2);
      assert.strictEqual(items.getElapsed(5, 5), 2);
      assert.strictEqual(items.getElapsed(6, 6), -1);
      assert.strictEqual(items.getElapsed(7, 7), -1);

      items.add(6, 6, 6);
      items.add(7, 7, 7);
      items.remove(4, 4);
      assert.strictEqual(items.getLength(), 5);
      assert.strictEqual(items.getLifetime(6, 6), 6);
      assert.strictEqual(items.getLifetime(7, 7), 7);
      assert.strictEqual(items.getElapsed(6, 6), 0);
      assert.strictEqual(items.getElapsed(7, 7), 0);
      items.tick(1);

      assert.strictEqual(items.getLength(), 4);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), false);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), true);
      assert.strictEqual(items.existsAt(4, 4), false);
      assert.strictEqual(items.existsAt(5, 5), true);
      assert.strictEqual(items.existsAt(6, 6), true);
      assert.strictEqual(items.existsAt(7, 7), true);
      assert.strictEqual(items.getElapsed(0, 0), -1);
      assert.strictEqual(items.getElapsed(1, 1), -1);
      assert.strictEqual(items.getElapsed(2, 2), -1);
      assert.strictEqual(items.getElapsed(3, 3), 3);
      assert.strictEqual(items.getElapsed(4, 4), -1);
      assert.strictEqual(items.getElapsed(5, 5), 3);
      assert.strictEqual(items.getElapsed(6, 6), 1);
      assert.strictEqual(items.getElapsed(7, 7), 1);

      items.tick(2);

      assert.strictEqual(items.getLength(), 3);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), false);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), false);
      assert.strictEqual(items.existsAt(4, 4), false);
      assert.strictEqual(items.existsAt(5, 5), true);
      assert.strictEqual(items.existsAt(6, 6), true);
      assert.strictEqual(items.existsAt(7, 7), true);
      assert.strictEqual(items.getElapsed(0, 0), -1);
      assert.strictEqual(items.getElapsed(1, 1), -1);
      assert.strictEqual(items.getElapsed(2, 2), -1);
      assert.strictEqual(items.getElapsed(3, 3), -1);
      assert.strictEqual(items.getElapsed(4, 4), -1);
      assert.strictEqual(items.getElapsed(5, 5), 5);
      assert.strictEqual(items.getElapsed(6, 6), 3);
      assert.strictEqual(items.getElapsed(7, 7), 3);

      items.tick(0.5);

      assert.strictEqual(items.getLength(), 2);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), false);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), false);
      assert.strictEqual(items.existsAt(4, 4), false);
      assert.strictEqual(items.existsAt(5, 5), false);
      assert.strictEqual(items.existsAt(6, 6), true);
      assert.strictEqual(items.existsAt(7, 7), true);
      assert.strictEqual(items.getElapsed(0, 0), -1);
      assert.strictEqual(items.getElapsed(1, 1), -1);
      assert.strictEqual(items.getElapsed(2, 2), -1);
      assert.strictEqual(items.getElapsed(3, 3), -1);
      assert.strictEqual(items.getElapsed(4, 4), -1);
      assert.strictEqual(items.getElapsed(5, 5), -1);
      assert(approximatelyEqual(items.getElapsed(6, 6), 3.5));
      assert(approximatelyEqual(items.getElapsed(7, 7), 3.5));

      items.tick(3.3);

      assert.strictEqual(items.getLength(), 1);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), false);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), false);
      assert.strictEqual(items.existsAt(4, 4), false);
      assert.strictEqual(items.existsAt(5, 5), false);
      assert.strictEqual(items.existsAt(6, 6), false);
      assert.strictEqual(items.existsAt(7, 7), true);
      assert.strictEqual(items.getElapsed(0, 0), -1);
      assert.strictEqual(items.getElapsed(1, 1), -1);
      assert.strictEqual(items.getElapsed(2, 2), -1);
      assert.strictEqual(items.getElapsed(3, 3), -1);
      assert.strictEqual(items.getElapsed(4, 4), -1);
      assert.strictEqual(items.getElapsed(5, 5), -1);
      assert.strictEqual(items.getElapsed(6, 6), -1);
      assert(approximatelyEqual(items.getElapsed(7, 7), 6.8));

      items.tick(1);

      assert.strictEqual(items.getLength(), 0);
      assert.strictEqual(items.existsAt(0, 0), false);
      assert.strictEqual(items.existsAt(1, 1), false);
      assert.strictEqual(items.existsAt(2, 2), false);
      assert.strictEqual(items.existsAt(3, 3), false);
      assert.strictEqual(items.existsAt(4, 4), false);
      assert.strictEqual(items.existsAt(5, 5), false);
      assert.strictEqual(items.existsAt(6, 6), false);
      assert.strictEqual(items.existsAt(7, 7), false);
      assert.strictEqual(items.getElapsed(0, 0), -1);
      assert.strictEqual(items.getElapsed(1, 1), -1);
      assert.strictEqual(items.getElapsed(2, 2), -1);
      assert.strictEqual(items.getElapsed(3, 3), -1);
      assert.strictEqual(items.getElapsed(4, 4), -1);
      assert.strictEqual(items.getElapsed(5, 5), -1);
      assert.strictEqual(items.getElapsed(6, 6), -1);
      assert.strictEqual(items.getElapsed(7, 7), -1);
    });
  });
});

function approximatelyEqual(num1: number, num2: number, epsilon: number = 0.00001) {
  return Math.abs(num1 - num2) < epsilon;
}
